# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the AEGIS security module
#

obj-$(CONFIG_SECURITY_AEGIS) += aegis.o

aegis-y := aegis_lsm.o \
	   aegis_process.o \
	   aegis_file.o \
	   aegis_audit.o \
	   aegis_module.o \
	   aegis_securityfs.o \
	   aegis_sysctl.o
